In [2]:
!pip install numpy
import numpy as np

In [6]:
x = np.array([[10,20],[30,40]])
print(x)

[[10 20]
 [30 40]]


In [7]:
sq = x ** 2
print(sq)

[[ 100  400]
 [ 900 1600]]


In [8]:
hundred = x + 100
print(hundred)

[[110 120]
 [130 140]]


In [9]:
five = x * 5
print(five)

[[ 50 100]
 [150 200]]


In [11]:
sqrt = x ** (1/2)
print(sqrt)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [25]:
arr1 = np.arange(3,30,3)
arr1.reshape(3,3)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [30]:
arr2 = np.arange(10,20,(10/9))
arr2.reshape(3,3)

array([[10.        , 11.11111111, 12.22222222],
       [13.33333333, 14.44444444, 15.55555556],
       [16.66666667, 17.77777778, 18.88888889]])

In [31]:
np.multiply(arr1, arr2)

array([ 30.        ,  66.66666667, 110.        , 160.        ,
       216.66666667, 280.        , 350.        , 426.66666667,
       510.        ])

In [35]:
p1 = np.load('process1.npy')
p2 = np.load('process2.npy')
p3 = np.load('process3.npy')
p4 = np.load('process4.npy')
p5 = np.load('process5.npy')

In [39]:
data = np.vstack((p1,p2,p3,p4,p5))
print(data)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


In [45]:
new_data = data.sum(axis=0)

In [46]:
data_mean = new_data / 5
print(data_mean)

[72.  27.8 45.6 12.  47.8]
